# Generated by Django 5.2.5 on 2026-02-14 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_data', models.JSONField(help_text='Ordered list of reports and coordinates')),
                ('total_distance', models.FloatField(default=0.0, help_text='Total distance in km')),
                ('is_completed', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
