# Generated by Django 5.2.7 on 2025-10-31 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('paper', 'Paper/Cardboard'), ('metal', 'Metal'), ('glass', 'Glass'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous'), ('general', 'General')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Collector'), ('collected', 'Collected'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='reports_was_status_16a7fa_idx'), models.Index(fields=['created_at'], name='reports_was_created_ce0be3_idx'), models.Index(fields=['user'], name='reports_was_user_id_649786_idx')],
            },
        ),
    ]
