# Generated by Django 5.2.5 on 2026-02-23 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_wastereport_collector'),
        ('scheduling', '0003_region_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='estimated_fullness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.region'),
        ),
    ]
