# Generated by Django 5.2.5 on 2026-02-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_wastereport_estimated_fullness_wastereport_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='threshold_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
