# Generated by Django 5.2.5 on 2026-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_wastereport_threshold_bonus_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Collector'), ('collected', 'Collected'), ('verified', 'Verified'), ('rejected', 'Rejected/Inaccurate')], default='pending', max_length=20),
        ),
    ]
