# Generated by Django 5.2.5 on 2026-02-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_wastereport_admin_feedback_alter_wastereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='collector_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='collector_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_photos/'),
        ),
    ]
