# Generated by Django 5.2.5 on 2026-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_wastereport_collector_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='points_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
