# Generated by Django 5.2.7 on 2025-10-30 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+2547xxxxxxxx' or '+2541xxxxxxxx'", regex='^\\\\+254[17]\\\\d{8}$')]),
        ),
    ]
