# Generated by Django 5.2.7 on 2025-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('collector', 'Collector'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
