# Generated by Django 5.2.5 on 2026-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('collector', 'Collector'), ('admin', 'Admin'), ('resident', 'Resident')], max_length=20),
        ),
    ]
