# Generated by Django 5.2.5 on 2026-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('collector', 'Collector'), ('admin', 'Admin'), ('citizen', 'Citizen')], max_length=20),
        ),
    ]
