# Generated by Django 5.2.5 on 2026-02-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionschedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
