# Generated by Django 5.2.5 on 2026-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_collectionschedule_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='threshold',
            field=models.IntegerField(default=100),
        ),
    ]
