# Generated by Django 5.2.5 on 2026-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_region_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
